# Generated by Django 3.1.7 on 2022-02-27 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=128, null=True, verbose_name='Description')),
                ('answer_time', models.PositiveIntegerField(default=0, verbose_name='Answer time')),
                ('uuid_testing', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID Field')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Question')),
                ('image', models.FileField(blank=True, null=True, upload_to='test_images', verbose_name='Test image')),
                ('type_answer_question', models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('RADIO', 'Radio button')], default='CHECKBOX', max_length=30)),
                ('uuid_question', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID Field')),
                ('testing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.testing', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Answer')),
                ('uuid_answer', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID Field')),
                ('correct_answer', models.BooleanField(default=False, verbose_name='Correct answer')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answer',
            },
        ),
    ]
