# Generated by Django 3.1.7 on 2022-04-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_answer_question',
            field=models.BooleanField(default=False),
        ),
    ]
