# Generated by Django 3.1.7 on 2022-04-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20220414_1312'),
        ('testing', '0003_auto_20220413_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='question',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='features.competence', verbose_name='Competence'),
        ),
        migrations.AddField(
            model_name='testing',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='features.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='testing',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='features.specialization', verbose_name='Specialization'),
        ),
    ]
