# Generated by Django 3.1.7 on 2022-06-05 13:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_testing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='testing_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=[], size=None, verbose_name='Test'),
        ),
    ]
