# Generated by Django 4.0.2 on 2022-02-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('DEAN', 'Dean')], default='STUDENT', max_length=10, verbose_name='User status'),
        ),
    ]
