# Generated by Django 3.1.7 on 2022-04-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20220414_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='description',
        ),
        migrations.AddField(
            model_name='discipline',
            name='competences',
            field=models.ManyToManyField(to='features.Competence', verbose_name='Competences'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='features.specialization', verbose_name='Specialization'),
        ),
    ]
