# Generated by Django 3.1.7 on 2022-04-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20220414_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
    ]
