# Generated by Django 3.1.7 on 2022-06-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20220414_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Name')),
                ('competences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.competence', verbose_name='Competence')),
            ],
            options={
                'verbose_name': 'Competence',
                'verbose_name_plural': 'Competences',
            },
        ),
    ]
