# Generated by Django 3.1.7 on 2022-06-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20220605_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicator'},
        ),
    ]
