# Generated by Django 3.1.7 on 2022-06-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_auto_20220605_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Type'),
        ),
    ]
