# Generated by Django 3.1.7 on 2022-06-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20220614_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
