# Generated by Django 3.1.7 on 2022-06-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_auto_20220614_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='competences',
            new_name='competence',
        ),
    ]
