# Generated by Django 3.1.7 on 2022-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20220614_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='type',
        ),
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=models.TextField(blank=True, verbose_name='Name'),
        ),
    ]
