# Generated by Django 3.1.7 on 2022-06-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_auto_20220614_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='features.specialization', verbose_name='Specialization'),
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
    ]
